spring:
  application:
    name: registration-service
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?createDatabaseIfNotExist=true
    username: root
    password: mysqldbpwd
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    tomcat:
      max-wait: 20000
      max-active: 50
      max-idle: 20
      min-idle: 15
    schema: classpath:schema.sql
    data: classpath:import.sql
    platform: mysql
  jpa:
    show-sql: true
    #    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
##  cache:
##    type: hazelcast
##    cache-names: usersCache
security:
  oauth2:
    resource:
      filter-order: 3