spring:
  application:
    name: adhesion-service
  datasource:
    url: jdbc:h2:mem:testdb;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
    schema: classpath:schema.sql
    data: classpath:data.sql
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true


#spring:
#  application:
#    name: adhesion-service
#  datasource:
#    url: jdbc:mysql://testdb:3306/testdb?autoReconnect=true&useSSL=false
#    username: root
#    password: mysqldbpwd
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    initialization-mode: always
#    tomcat:
#      max-wait: 20000
#      max-active: 50
#      max-idle: 20
#      min-idle: 15
#    schema: classpath:schema.sql
#    data: classpath:data.sql
#    platform: mysql
#  jpa:
#    show-sql: true
##    database-platform: org.hibernate.dialect.H2Dialect
#    database: mysql
#    hibernate:
#      ddl-auto: create-drop
#    #      naming:
#    #        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#    properties:
#      hibernate:
#        use_sql_comments: true
#        format_sql: true