
INSERT INTO USERS(ID, USER_NAME, PASSWORD, ACCOUNT_EXPIRED, ACCOUNT_LOCKED, CREDENTIALS_EXPIRED, ENABLED)
VALUES (1, 'martin', 'martin', FALSE, FALSE, FALSE, TRUE);


INSERT INTO AUTHORITY(ID, NAME) VALUES (1, 'ROLE_CLIENT');

INSERT INTO USERS_AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (1, 1);
