DROP TABLE IF EXISTS AUTHORITY;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS USERS_AUTHORITIES;

CREATE TABLE AUTHORITY
(
  ID   BIGINT NOT NULL auto_increment,
  NAME VARCHAR(255),
  PRIMARY KEY (ID)
);

ALTER TABLE AUTHORITY
  ADD CONSTRAINT AUTHORITY_NAME UNIQUE (NAME);

CREATE TABLE USERS
(
  ID                  BIGINT NOT NULL auto_increment,
  PASSWORD            VARCHAR(255),
  USER_NAME           VARCHAR(255),
  ACCOUNT_EXPIRED     BOOLEAN,
  ACCOUNT_LOCKED      BOOLEAN,
  CREDENTIALS_EXPIRED BOOLEAN,
  ENABLED             BOOLEAN,
  PRIMARY KEY (ID)
);

ALTER TABLE USERS
  ADD CONSTRAINT USER_USER_NAME UNIQUE (USER_NAME);

CREATE TABLE USERS_AUTHORITIES
(
  USER_ID      BIGINT NOT NULL,
  AUTHORITY_ID BIGINT NOT NULL,
  PRIMARY KEY (USER_ID, AUTHORITY_ID)
);

ALTER TABLE USERS_AUTHORITIES
  ADD CONSTRAINT `fk_users_authorities_authority`
    FOREIGN KEY (AUTHORITY_ID) REFERENCES AUTHORITY(ID);

ALTER TABLE USERS_AUTHORITIES
  ADD CONSTRAINT `fk_users_authorities_users`
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID);